'use strict';
const JOBS={lumber:{name:'나무꾼',person:'도윤',emoji:'',building:'forest',output:'wood',rate:5,cost:30,description:'숲에서 나무를 모아요',unit:'나무'},farmer:{name:'농부',person:'하나',emoji:'',building:'farm',output:'food',rate:5,cost:30,description:'밭에서 식량을 길러요',unit:'식량'},teacher:{name:'선생님',person:'서연',emoji:'',building:'school',output:'knowledge',rate:3,cost:60,description:'학교에서 지식을 쌓아요',unit:'지식'},merchant:{name:'상인',person:'민준',emoji:'',building:'market',output:'gold',rate:8,cost:50,description:'시장에 손님을 모아요',unit:'골드'},builder:{name:'광부',person:'지호',emoji:'',building:'mine',output:'gold',rate:12,cost:70,description:'광산에서 금을 캐요',unit:'골드'}};
const BUILDINGS={house:{name:'집',emoji:'',cost:{gold:40,wood:25},desc:'직원 자리 2개를 더해요'},forest:{name:'숲',emoji:'',cost:{gold:20},desc:'나무꾼이 일하는 곳'},farm:{name:'밭',emoji:'',cost:{gold:30,wood:10},desc:'농부가 일하는 곳'},school:{name:'학교',emoji:'',cost:{gold:80,wood:40,food:20},desc:'선생님이 일하는 곳'},market:{name:'시장',emoji:'',cost:{gold:50,wood:25},desc:'상인이 일하는 곳'},mine:{name:'광산',emoji:'',cost:{gold:100,wood:40,knowledge:15},desc:'광부가 일하는 곳'}};
function spriteMarkup(col,row){return `<span class="sprite" style="--sx:${col/3*100}%;--sy:${row/3*100}%" aria-hidden="true"></span>`}
Object.entries(JOBS).forEach(([id,j],i)=>j.emoji=spriteMarkup(i===0?0:i-1,i===0?1:2));
Object.entries(BUILDINGS).forEach(([id,b])=>b.emoji=spriteMarkup(({house:0,forest:1,farm:2,school:3,market:0,mine:1})[id],3));
const LABELS={gold:'골드',wood:'나무',food:'식량',knowledge:'지식'};const key='little-village-v1';
function fresh(){return{version:1,name:'새싹 마을',gold:140,wood:30,food:20,knowledge:0,xp:0,ticks:0,paused:false,tiles:Array.from({length:20},(_,i)=>i===7?{type:'house',worker:null}:i===6?{type:'forest',worker:null}:i===8?{type:'farm',worker:null}:null),workers:[],quests:0}}
let state=fresh();try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.version===1&&Array.isArray(saved.tiles)&&saved.tiles.length===20&&Array.isArray(saved.workers)&&Object.keys(LABELS).every(k=>Number.isFinite(saved[k])&&saved[k]>=0))state=saved}catch(e){}
let tab='staff',selectedJob=null,selectedBuild=null,selectedTile=null,toastTimer;const $=id=>document.getElementById(id);
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000)}
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch(e){$('save').textContent='이 브라우저에서는 저장할 수 없어요. 창을 닫으면 진행 상황이 사라질 수 있어요.'}}
function capacity(){return state.tiles.filter(t=>t?.type==='house').length*2}function costText(cost){return Object.entries(cost).map(([k,v])=>LABELS[k]+' '+v).join(' · ')}function afford(cost){return Object.entries(cost).every(([k,v])=>state[k]>=v)}function pay(cost){Object.entries(cost).forEach(([k,v])=>state[k]-=v)}function level(){return 1+Math.floor(state.xp/60)}function income(){const out={gold:2,wood:0,food:0,knowledge:0};state.tiles.forEach(t=>{if(t?.worker){const j=JOBS[t.worker];out[j.output]+=j.rate}});return out}
function render(){for(const k in LABELS)$ (k).textContent=Math.floor(state[k]).toLocaleString('ko-KR');$('villageTitle').textContent=state.name;$('day').textContent=1+Math.floor(state.ticks/6);$('level').textContent=`Lv. ${level()} · ${level()<3?'작은 시작':level()<6?'성장하는 마을':'활기찬 마을'}`;$('population').textContent=`직원 ${state.workers.length} / ${capacity()}명`;$('xpbar').style.width=state.xp%60/60*100+'%';$('pause').textContent=state.paused?'▶ 계속하기':'⏸ 일시정지';
$('map').innerHTML=state.tiles.map((t,i)=>t?`<button class="tile ${t.worker?'working':''} ${selectedTile===i?'selected':''}" data-tile="${i}" aria-label="${i+1}번 땅 ${BUILDINGS[t.type].name}${t.worker?' '+JOBS[t.worker].name+' 일하는 중':''}"><span class="emoji">${BUILDINGS[t.type].emoji}</span><span class="tilename">${BUILDINGS[t.type].name}</span><span class="status">${t.type==='house'?'직원 자리 +2':t.worker?'일하는 중':'직원 대기'}</span>${t.worker?`<span class="worker">${JOBS[t.worker].emoji}</span>`:''}</button>`:`<button class="tile empty ${selectedTile===i?'selected':''}" data-tile="${i}" aria-label="${i+1}번 빈 땅에 건물 짓기"><span class="emoji" style="font-size:25px">＋</span><span class="tilename">빈 땅</span></button>`).join('');renderCatalog();renderQuest();}
function renderCatalog(){$('staffTab').classList.toggle('active',tab==='staff');$('buildTab').classList.toggle('active',tab==='build');$('panelHint').textContent=tab==='staff'?'직원을 고른 다음, 일할 건물을 눌러 장착하세요.':'건물을 고른 다음, 마을의 빈 땅을 눌러 지으세요.';
$('catalog').innerHTML=tab==='staff'?Object.entries(JOBS).map(([id,j])=>{const hired=state.workers.includes(id),assigned=state.tiles.some(t=>t?.worker===id);return`<div class="card ${selectedJob===id?'chosen':''}"><div class="portrait">${j.emoji}</div><div class="cardtext"><b>${j.name} <small>${j.person} · ${assigned?'일하는 중':hired?'장착 가능':'고용 가능'}</small></b><p>${j.unit} +${j.rate} / 5초</p><small>${hired?j.description:'고용 골드 '+j.cost}</small></div><button class="choose" data-job="${id}">${selectedJob===id?'선택됨':assigned?'이동':hired?'장착':'고용'}</button></div>`}).join(''):Object.entries(BUILDINGS).map(([id,b])=>`<div class="card ${selectedBuild===id?'chosen':''}"><div class="portrait">${b.emoji}</div><div class="cardtext"><b>${b.name}</b><p>${b.desc}</p><small>${costText(b.cost)}</small></div><button class="choose" data-build="${id}">${selectedBuild===id?'선택됨':'선택'}</button></div>`).join('');}
const QUESTS=[{title:'첫 번째 출근',desc:'나무꾼과 농부를 고용해서 숲과 밭에 장착하기',check:()=>['lumber','farmer'].every(j=>state.tiles.some(t=>t?.worker===j)),reward:70},{title:'배움이 자라는 마을',desc:'학교를 짓고 선생님 장착하기',check:()=>state.tiles.some(t=>t?.worker==='teacher'),reward:100},{title:'북적북적한 시장',desc:'시장을 짓고 상인 장착하기',check:()=>state.tiles.some(t=>t?.worker==='merchant'),reward:120},{title:'모두의 마을',desc:'다섯 직원을 모두 일하게 하기',check:()=>Object.keys(JOBS).every(j=>state.tiles.some(t=>t?.worker===j)),reward:180}];
function renderQuest(){const q=QUESTS[state.quests];$('objective').innerHTML=q?`<strong> ${q.title}</strong>${q.desc}<br><span>완료 보상:  ${q.reward}</span>`:'<strong> 멋진 마을 완성!</strong>모든 직원이 일을 하고 있어요. 남은 땅도 자유롭게 꾸며 보세요.'}
function checkQuest(){const q=QUESTS[state.quests];if(q&&q.check()){state.gold+=q.reward;state.xp+=20;state.quests++;toast(` ${q.title} 완료! 골드 +${q.reward}`);$('feed').textContent=` ${q.title} 완료! 마을이 한 걸음 더 자랐어요.`;}}
function update(){checkQuest();save();render()}function open(html){$('dialogContent').innerHTML=html;$('dialog').showModal()}function close(){$('dialog').close()}
function hire(id){const j=JOBS[id];if(!state.workers.includes(id)){if(state.workers.length>=capacity()){toast('집을 더 지으면 직원을 더 고용할 수 있어요!');return}if(state.gold<j.cost){toast('골드가 부족해요. 마을 지원금이 5초마다 2골드씩 들어와요.');return}state.gold-=j.cost;state.workers.push(id);toast(`${j.name} ${j.person} 고용! ${BUILDINGS[j.building].name}을 눌러 장착하세요.`)}selectedJob=id;selectedBuild=null;selectedTile=null;update()}
function build(i,type){const b=BUILDINGS[type];if(state.tiles[i])return;if(!afford(b.cost)){toast('자원이 부족해요. 직원들이 모아 올 때까지 기다려 주세요.');return}pay(b.cost);state.tiles[i]={type,worker:null};state.xp+=10;selectedTile=null;selectedBuild=null;close();toast(`${b.name}을 지었어요!`);update()}
function assign(i,id){const j=JOBS[id],t=state.tiles[i];if(!state.workers.includes(id)){toast('먼저 직원을 고용해 주세요.');return}if(t?.type!==j.building){toast(`${j.name}은 ${BUILDINGS[j.building].name}에서 일해요!`);return}if(t.worker&&t.worker!==id){toast('이미 다른 직원이 일하고 있어요.');return}state.tiles.forEach(t=>{if(t?.worker===id)t.worker=null});t.worker=id;selectedJob=null;selectedTile=null;close();toast(`${j.name} ${j.person}, 일을 시작했어요!`);update()}
function tileClick(i){const t=state.tiles[i];if(!t){if(selectedBuild){build(i,selectedBuild);return}selectedTile=i;render();open(`<h2> 여기에 무엇을 지을까요?</h2><p>건물을 선택하면 바로 지어져요.</p>${Object.entries(BUILDINGS).map(([id,b])=>`<button class="action ${!afford(b.cost)?'secondary':''}" data-place="${id}" data-index="${i}">${b.emoji} ${b.name} · ${costText(b.cost)}</button>`).join('')}`);return}if(selectedJob){assign(i,selectedJob);return}selectedTile=i;render();const worker=t.worker?JOBS[t.worker]:null;const job=Object.entries(JOBS).find(([id,j])=>j.building===t.type);open(`<h2>${BUILDINGS[t.type].emoji} ${BUILDINGS[t.type].name}</h2>${t.type==='house'?'<p>이 집이 직원 2명의 자리를 마련해 줘요.</p>':worker?`<div class="jobline">${worker.emoji} ${worker.name} ${worker.person}<br>${worker.unit} +${worker.rate} / 5초</div><button class="action secondary" data-unassign="${i}">직원 장착 해제</button>`:`<p>아직 직원이 없어요.</p>${job?`<button class="action" data-station="${job[0]}" data-index="${i}">${JOBS[job[0]].emoji} ${JOBS[job[0]].name} ${state.workers.includes(job[0])?'장착':'고용 후 장착 ( '+JOBS[job[0]].cost+')'}</button>`:''}`}`)}
$('map').addEventListener('click',e=>{const b=e.target.closest('[data-tile]');if(b)tileClick(Number(b.dataset.tile))});$('catalog').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.job)hire(b.dataset.job);if(b.dataset.build){selectedBuild=b.dataset.build;selectedJob=null;toast(`${BUILDINGS[selectedBuild].name}을 지을 빈 땅을 눌러 주세요.`);render()}});
$('dialogContent').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.place)build(Number(b.dataset.index),b.dataset.place);if(b.dataset.station){const id=b.dataset.station;hire(id);if(state.workers.includes(id))assign(Number(b.dataset.index),id)}if(b.dataset.unassign!==undefined){state.tiles[Number(b.dataset.unassign)].worker=null;close();update()}if(b.id==='rename'){const input=$('nameInput');const name=input.value.trim();if(name){state.name=name.slice(0,20);close();update()}}});
$('staffTab').onclick=()=>{tab='staff';selectedBuild=null;render()};$('buildTab').onclick=()=>{tab='build';selectedJob=null;render()};$('pause').onclick=()=>{state.paused=!state.paused;update()};$('closeDialog').onclick=close;$('dialog').addEventListener('close',()=>{selectedTile=null;render()});$('help').onclick=()=>open('<p>방향키, WASD 또는 방향 버튼으로 내 캐릭터를 움직여요. 마을의 건물이나 빈 터를 누르면 상호작용할 수 있어요. 나무꾼은 도끼질을 하며 자원을 모아요.</p><h2> 마을을 키우는 방법</h2><p>1. 직원을 고용하고 직업에 맞는 건물을 눌러 장착해요.</p><p>2. 일하는 직원이 5초마다 자원을 모아요. 마을 지원금도 2골드씩 들어와요.</p><p>3. 모은 자원으로 집, 학교, 시장을 지어요. 집 1채마다 직원 2명을 고용할 수 있어요.</p><p>4. 선생님이 모은 지식으로 광산을 지을 수 있어요. 일할 때마다 마을 경험치도 올라요.</p><p>게임은 화면이 열려 있을 때 진행돼요. 진행 상황은 이 기기에만 자동 저장돼요.</p>');$('villageTitle').style.cursor='pointer';$('villageTitle').onclick=()=>{open('<h2>우리 마을 이름</h2><input id="nameInput" maxlength="20" aria-label="마을 이름"><button id="rename" class="action">이 이름으로 바꾸기</button>');$('nameInput').value=state.name};
setInterval(()=>{if(state.paused||document.hidden)return;const inc=income();Object.entries(inc).forEach(([k,v])=>state[k]+=v);state.ticks++;const working=state.tiles.filter(t=>t?.worker).length;state.xp+=working;$('feed').textContent=working?` 직원 ${working}명이 일했어요! `+Object.entries(inc).filter(([k,v])=>v>0).map(([k,v])=>`${LABELS[k]} +${v}`).join(' · '):' 마을 지원금 +2 · 첫 직원을 고용해 보세요!';update()},5000);window.addEventListener('pagehide',save);render();
