'use strict';
const canvas=$('world'),ctx=canvas.getContext('2d'),W=900,H=680,CW=160,CH=140,OX=50,OY=75;
const atlas=new Image(),scenes=new Image(),oldArt=new Image();let assets=0,assetFailure=false;
function ready(){assets++;if(assets===3&&!assetFailure)$('worldLoading').style.display='none'}
function failed(){assetFailure=true;$('worldLoading').textContent='그림을 불러오지 못했어요. 새로고침해 주세요.'}
for(const image of[atlas,scenes,oldArt]){image.onload=ready;image.onerror=failed}atlas.src='cozy-sprites.webp';scenes.src='cozy-scenes.webp';oldArt.src='village-sprites.webp';
const cozyKey='little-village-story-v1';function newStory(){return{version:1,day:1,clock:0,scene:'outside',sleepLeft:0,woke:false,quest:0,pet:null,fed:{},visitors:[],raidDone:0,raidDay:0,player:{x:450,y:620,direction:'down'},attack:0,returned:false}}
let cozy=newStory();try{const c=JSON.parse(localStorage.getItem(cozyKey));if(c?.version===1&&Number.isFinite(c.day)&&Number.isFinite(c.clock)&&Array.isArray(c.visitors)&&c.player&&['outside','inside','sleeping'].includes(c.scene)){cozy={...cozy,...c};if(cozy.pet&&!['cat','dog','rabbit'].includes(cozy.pet))cozy.pet=null}}catch(e){}
let player=cozy.player,keys=new Set(),lastTime=0,animTime=0,moving=false,uiTime=0,saveTime=0,attackPoint=null;
const CATS=[{id:'ginger',name:'치즈',col:0,x:630,y:405,t:0},{id:'gray',name:'구름',col:1,x:725,y:540,t:2},{id:'small',name:'콩이',col:0,x:360,y:510,t:4}];let follower={x:player.x-48,y:player.y+25};
function cell(i){return{x:OX+(i%5)*CW+CW/2,y:OY+Math.floor(i/5)*CH+CH/2}}
const cute=(col,row)=>`<span class="sprite cutesprite" style="--sx:${col/3*100}%;--sy:${row/3*100}%" aria-hidden="true"></span>`;
JOBS.lumber.emoji=cute(0,1);JOBS.lumber.person='도토리';JOBS.lumber.description='꼬마 나무꾼이 나무를 모아요';
function saveStory(){cozy.player=player;try{localStorage.setItem(cozyKey,JSON.stringify(cozy))}catch(e){$('save').textContent='이 브라우저에서는 저장할 수 없어요.'}}
function phase(){return cozy.clock<60?'아침':cozy.clock<85?'낮':cozy.clock<100?'저녁':'밤'}
const goals=[{title:'꼬마 나무꾼과 친구가 되자!',desc:'나무꾼 도토리를 고용하고 숲에 장착해 주세요.',done:()=>state.tiles.some(t=>t?.worker==='lumber')},{title:'나만의 작은 펫을 만나자!',desc:'고양이, 강아지, 토끼 중 내 펫을 골라 주세요.',done:()=>!!cozy.pet},{title:'말썽꾸러기 아저씨, 돌아가 주세요!',desc:'아저씨 한 명당 5번 눌러 마을을 지켜 주세요.',done:()=>cozy.raidDone>0},{title:'별이 뜨면 우리 집으로!',desc:'밤이 되면 집을 누르거나 집에 들어가기 버튼을 눌러요.',done:()=>cozy.clock>=100&&cozy.scene==='inside'},{title:'포근한 침대에서 코오 자요',desc:'침대를 누르거나 잠자기 버튼을 눌러 주세요.',done:()=>cozy.scene==='sleeping'||cozy.woke},{title:'좋은 아침! 문으로 나가자',desc:'몇 초 자고 일어나면 문을 눌러 밖으로 나가요.',done:()=>cozy.returned},{title:'길고양이들에게 밥을 주자!',desc:'치즈, 구름, 콩이에게 식량 1개씩 주세요. 오늘 하루 따라와요.',done:()=>CATS.every(c=>cozy.fed[c.id]===cozy.day)}];
function currentGoal(){if(cozy.quest<goals.length)return goals[cozy.quest];if(cozy.scene==='sleeping')return{title:'포근하게 코오…',desc:'조금만 기다리면 다시 아침이 돼요.'};if(cozy.woke&&cozy.scene==='inside')return{title:'좋은 아침! 문으로 나가요',desc:'문을 누르면 새로운 하루가 시작돼요.'};if(cozy.visitors.length)return{title:'말썽 아저씨를 돌려보내요!',desc:'한 명당 5번 눌러 주세요. 내 캐릭터가 귀엽게 맞서요.'};if(cozy.clock>=100)return{title:'별빛 아래 집으로 돌아가요',desc:'집에 들어가 침대에서 쉬어요.'};if(!CATS.every(c=>cozy.fed[c.id]===cozy.day))return{title:'길고양이들에게 아침밥을!',desc:'고양이를 누르면 식량 1개로 밥을 줘요. 오늘만 따라와요.'};return{title:'친구들과 우리 마을을 키워요!',desc:'건물을 짓고 직원을 장착해요. 밤에는 집에서 코오 자요.'}}
function advanceStory(){let count=0;while(cozy.quest<goals.length&&goals[cozy.quest].done()&&count++<7){cozy.quest++;state.gold+=20;state.xp+=10;toast('목표 완료! 참 잘했어요 · 골드 +20');$('storyGoal').classList.remove('celebrate');void $('storyGoal').offsetWidth;$('storyGoal').classList.add('celebrate');save();saveStory()}if(cozy.quest===2&&cozy.raidDay!==cozy.day)spawnRaid()}
renderQuest=()=>{};const originalRender=render;render=function(){originalRender();storyUI()};
function storyUI(){const q=currentGoal();$('storyGoal').innerHTML=`<small>오늘의 작은 목표</small><strong>${q.title}</strong><p>${q.desc}</p>`;$('day').textContent=cozy.day;$('dayPhase').textContent=cozy.scene==='sleeping'?'꿈나라':phase();$('sceneTag').textContent=cozy.scene==='outside'?(phase()==='밤'?'별이 반짝이는 밤 · 집으로 돌아가요':phase()==='저녁'?'노을빛 마을 · 곧 밤이 돼요':'햇살 가득한 우리 마을'):cozy.scene==='sleeping'?`코오… 아침까지 ${Math.ceil(cozy.sleepLeft)}초`:cozy.woke?'좋은 아침! 문으로 나가 볼까요?':'포근한 우리 집';document.querySelector('.village').classList.toggle('scene-dark',cozy.clock>=85&&cozy.scene==='outside');$('homeAction').textContent=cozy.scene==='outside'?'집에 들어가기':cozy.scene==='sleeping'?'코오 자는 중…':cozy.clock>=100?'침대에서 잠자기':'문으로 나가기';$('homeAction').disabled=cozy.scene==='sleeping';$('petAction').textContent=cozy.pet?'내 펫 바꾸기':'내 펫 고르기';$('storyHint').textContent=cozy.scene==='outside'?'고양이와 아저씨를 직접 눌러 보세요. 하루는 약 100초, 잠은 6초예요.':cozy.scene==='sleeping'?'포근한 이불 속에서 쿨쿨…':'밤에는 침대를 누르고, 아침에는 문을 눌러 나가요.';
const pet=cozy.pet?{cat:{name:'내 고양이',col:0},dog:{name:'내 강아지',col:2},rabbit:{name:'내 토끼',col:3}}[cozy.pet]:null;$('petStatus').innerHTML=pet?`<div class="petstatus">${cute(pet.col,2)}<span><b>${pet.name}</b><br>항상 내 곁을 따라와요</span></div>`:'<div class="petstatus">작은 친구를 골라 함께 걸어 보세요.</div>';
$('encounters').innerHTML=cozy.scene==='outside'?cozy.visitors.map(v=>`<div class="encounter">${cute(0,3)} 말썽 아저씨 · ${v.hits}/5번<button class="choose" data-visitor="${v.id}">아저씨 돌려보내기 (${5-v.hits}번 남음)</button></div>`).join('')+`<div class="catbuttons">${CATS.map(c=>`<button data-feed="${c.id}" ${cozy.fed[c.id]===cozy.day?'disabled':''}>${c.name} ${cozy.fed[c.id]===cozy.day?'오늘의 친구':'밥 주기 · 식량 1'}</button>`).join('')}</div>`:cozy.scene==='inside'?'<div class="encounter">우리 집<button class="choose" id="doorButton">문으로 나가기</button></div>':'';
}
function sprite(image,col,row,x,y,size=100,flip=false){if(assets<3)return;const sw=image.width/4,sh=image.height/4;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(image,col*sw,row*sh,sw,sh,-size/2,-size,size,size);ctx.restore()}
function background(col,row){if(assets<3)return;const sw=scenes.width/3,sh=scenes.height/2;ctx.drawImage(scenes,col*sw,row*sh,sw,sh,0,0,W,H)}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function label(text,x,y,color='#866376',size=15){ctx.font=`bold ${size}px ui-rounded,system-ui`;ctx.textAlign='center';const width=ctx.measureText(text).width+18;ctx.fillStyle='#fff8f3eb';ctx.beginPath();ctx.roundRect(x-width/2,y-18,width,26,10);ctx.fill();ctx.fillStyle=color;ctx.fillText(text,x,y)}
function collision(x,y){if(cozy.scene!=='outside')return false;return state.tiles.some((t,i)=>{if(!t)return false;const p=cell(i);return Math.abs(x-p.x)<34&&y>p.y-24&&y<p.y+2})}
function moveTowards(o,x,y,speed,dt){const dx=x-o.x,dy=y-o.y,d=Math.hypot(dx,dy);if(d>5){o.x+=dx/d*Math.min(d,speed*dt);o.y+=dy/d*Math.min(d,speed*dt)}}
function feedCat(id){if(cozy.scene!=='outside')return;if(cozy.fed[id]===cozy.day){toast('오늘 밥을 먹었어요. 이제 나를 따라와요!');return}if(state.food<1){toast('식량이 필요해요. 농부를 밭에 장착해 주세요.');return}state.food--;cozy.fed[id]=cozy.day;const fedCat=CATS.find(c=>c.id===id);fedCat.bowl={x:fedCat.x+20,y:fedCat.y+12,until:animTime+4};toast(`${CATS.find(c=>c.id===id).name}와 친해졌어요! 오늘 하루 따라와요.`);advanceStory();save();saveStory();render()}
function spawnRaid(){if(cozy.visitors.length||cozy.scene!=='outside')return;cozy.raidDay=cozy.day;cozy.visitors=[{id:'v'+cozy.day+'a',x:845,y:235,hits:0},{id:'v'+cozy.day+'b',x:845,y:500,hits:0}];toast('말썽 아저씨들이 왔어요! 한 명당 5번 눌러 주세요.');saveStory();storyUI()}
function hitVisitor(id){if(cozy.scene!=='outside'||state.paused)return;const v=cozy.visitors.find(v=>v.id===id);if(!v)return;v.hits++;cozy.attack=.55;attackPoint={x:v.x,y:v.y};player.direction=v.x<player.x?'left':'right';if(v.hits>=5){cozy.visitors=cozy.visitors.filter(x=>x.id!==id);toast('아저씨가 물러났어요! 안녕~');if(!cozy.visitors.length){cozy.raidDone++;state.gold+=25;advanceStory()}}save();saveStory();render()}
function enterHome(){if(cozy.scene!=='outside')return;cozy.scene='inside';cozy.visitors=[];cozy.woke=false;player.x=450;player.y=565;keys.clear();advanceStory();saveStory();render()}
function sleep(){if(cozy.scene!=='inside')return;if(cozy.clock<100){toast('아직 낮이에요. 밤이 되면 침대에서 잘 수 있어요.');return}cozy.scene='sleeping';cozy.sleepLeft=6;keys.clear();advanceStory();saveStory();render()}
function wake(){cozy.scene='inside';cozy.day++;cozy.clock=0;cozy.sleepLeft=0;cozy.woke=true;cozy.returned=false;cozy.fed={};cozy.visitors=[];player.x=300;player.y=380;toast('좋은 아침! 푹 잤어요. 문으로 나가 볼까요?');advanceStory();saveStory();render()}
function exitHome(){if(cozy.scene!=='inside')return;cozy.scene='outside';cozy.returned=cozy.day>1;cozy.woke=false;player.x=450;player.y=620;keys.clear();advanceStory();saveStory();render()}
function choosePet(){open(`<h2>내 작은 친구를 골라요</h2><p>골드 없이 만날 수 있어요. 내 펫은 매일 함께하고, 밥을 준 길고양이는 오늘만 따라와요.</p><div class="petoptions">${[{id:'cat',name:'포실포실 고양이',col:0},{id:'dog',name:'몽실몽실 강아지',col:2},{id:'rabbit',name:'말랑말랑 토끼',col:3}].map(p=>`<button class="petoption ${cozy.pet===p.id?'selected':''}" data-pet="${p.id}">${cute(p.col,2)}${p.name}</button>`).join('')}</div>`)}
$('dialogContent').addEventListener('click',e=>{const b=e.target.closest('[data-pet]');if(!b)return;cozy.pet=b.dataset.pet;follower={x:player.x-35,y:player.y+30};close();advanceStory();saveStory();render();toast('작은 친구가 내 펫이 되었어요!')});$('petAction').onclick=choosePet;$('homeAction').onclick=()=>{if(cozy.scene==='outside')enterHome();else if(cozy.scene==='inside'){if(cozy.clock>=100)sleep();else exitHome()}};
$('encounters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.visitor)hitVisitor(b.dataset.visitor);if(b.dataset.feed)feedCat(b.dataset.feed);if(b.id==='doorButton')exitHome()});
const originalTileClick=tileClick;tileClick=function(i){if(cozy.scene==='outside'&&state.tiles[i]?.type==='house'&&!selectedJob&&!selectedBuild){enterHome();return}originalTileClick(i)};
function draw(dt){const running=!state.paused&&!document.hidden&&!$('dialog').open;if(running){animTime+=dt;cozy.attack=Math.max(0,cozy.attack-dt);if(cozy.scene==='sleeping'){cozy.sleepLeft=Math.max(0,cozy.sleepLeft-dt);if(cozy.sleepLeft<=0)wake()}else{cozy.clock=Math.min(100,cozy.clock+dt);if(cozy.scene==='outside'&&cozy.clock>45&&cozy.raidDay!==cozy.day&&cozy.quest>=2)spawnRaid()}}
let dx=0,dy=0;if(running&&cozy.scene!=='sleeping'){if(keys.has('left'))dx--;if(keys.has('right'))dx++;if(keys.has('up'))dy--;if(keys.has('down'))dy++}moving=!!(dx||dy);if(moving){if(cozy.woke)cozy.woke=false;const n=Math.hypot(dx,dy),step=180*dt;const x=Math.max(30,Math.min(870,player.x+dx/n*step)),y=Math.max(70,Math.min(650,player.y+dy/n*step));if(!collision(x,player.y))player.x=x;if(!collision(player.x,y))player.y=y;player.direction=dy<0?'up':dx<0?'left':dx>0?'right':'down'}
ctx.clearRect(0,0,W,H);if(cozy.scene==='outside')drawOutside(dt,running);else drawInside();uiTime+=dt;saveTime+=dt;if(uiTime>.3){uiTime=0;advanceStory();storyUI()}if(saveTime>2){saveTime=0;saveStory()}}
function drawPlayer(){ellipse(player.x,player.y,21,6,'#704d5d30');const col=cozy.attack>0?3:moving?1+Math.floor(animTime*8)%2:0;const bob=moving?Math.sin(animTime*15)*3:Math.sin(animTime*2)*1;sprite(atlas,col,0,player.x,player.y+6+bob,110,player.direction==='left');label(cozy.attack>0?'얍! 돌아가요~':'나',player.x,player.y-100,'#a65e84',16);if(cozy.attack>0&&attackPoint){ctx.strokeStyle='#ffe3a6';ctx.lineWidth=4;for(let j=0;j<5;j++){const a=j*Math.PI*2/5;ctx.beginPath();ctx.moveTo(attackPoint.x+Math.cos(a)*14,attackPoint.y-40+Math.sin(a)*14);ctx.lineTo(attackPoint.x+Math.cos(a)*25,attackPoint.y-40+Math.sin(a)*25);ctx.stroke()}}}
function drawOutside(dt,running){background(cozy.clock>=100?2:cozy.clock>=85?1:0,1);const draws=[];state.tiles.forEach((t,i)=>{const p=cell(i);if(!t){ctx.strokeStyle=selectedBuild?'#d79f80':'#b8c39577';ctx.lineWidth=2;ctx.setLineDash([5,8]);ctx.beginPath();ctx.roundRect(p.x-42,p.y-45,84,52,12);ctx.stroke();ctx.setLineDash([]);if(selectedBuild)label('여기에 지어요',p.x,p.y-14,'#a07861',14);return}draws.push({y:p.y,fn:()=>{ellipse(p.x,p.y,38,9,'#735f3530');const col=({house:0,forest:1,farm:2,school:3,market:0,mine:1})[t.type];if(t.type==='house')sprite(atlas,3,3,p.x,p.y+12,126);else sprite(oldArt,col,3,p.x,p.y+12,t.type==='forest'?130:117);label(BUILDINGS[t.type].name,p.x,p.y+26)}});if(t.worker){const a={x:p.x-50,y:p.y+5},j=t.worker;draws.push({y:a.y,fn:()=>{if(j==='lumber'){const frame=running?Math.floor(animTime*3)%4:0;sprite(atlas,frame,1,a.x,a.y+6,96);label('꼬마 도토리',a.x,a.y-87,'#a66860',14)}else{const col=({farmer:0,teacher:1,merchant:2,builder:3})[j];sprite(oldArt,col,2,a.x,a.y+6+(running?Math.sin(animTime*4)*2:0),86)}if(running&&Math.floor(animTime)%5===0)label('+'+JOBS[j].rate,a.x,a.y-112-(animTime%1)*8,'#80a36c',14)}})}});
CATS.forEach((c,i)=>{if(c.bowl&&animTime<c.bowl.until)sprite(atlas,2,3,c.bowl.x,c.bowl.y,44);const following=cozy.fed[c.id]===cozy.day;if(running){if(following)moveTowards(c,player.x-65-i*28,player.y+40+i*12,120,dt);else{const targetX=500+Math.sin(animTime*.13+c.t)*250,targetY=420+Math.cos(animTime*.19+c.t)*145;moveTowards(c,targetX,targetY,25,dt)}}draws.push({y:c.y,fn:()=>{ellipse(c.x,c.y,16,5,'#685c4428');sprite(atlas,c.col,2,c.x,c.y+5+Math.sin(animTime*5+c.t)*1.5,70,c.x>player.x);label(following?c.name+' · 오늘의 친구':c.name+' · 밥 주세요',c.x,c.y-62,'#9b7b6b',13)}})});
if(cozy.pet){if(running)moveTowards(follower,player.x+55,player.y+25,145,dt);draws.push({y:follower.y,fn:()=>{sprite(atlas,({cat:0,dog:2,rabbit:3})[cozy.pet],2,follower.x,follower.y+5+Math.sin(animTime*5)*2,77);label('내 펫',follower.x,follower.y-68,'#a8748b',13)}})}
cozy.visitors.forEach((v,i)=>{if(running){const tx=620+i*95,ty=235+i*200;moveTowards(v,tx,ty,45,dt)}draws.push({y:v.y,fn:()=>{ellipse(v.x,v.y,22,7,'#68535e28');sprite(atlas,v.hits>0?1:0,3,v.x+Math.sin(animTime*5)*2,v.y+7,104);label('아저씨 '+v.hits+'/5',v.x,v.y-100,'#a87291',15)}})});draws.push({y:player.y,fn:drawPlayer});draws.sort((a,b)=>a.y-b.y).forEach(d=>d.fn());if(cozy.clock>=100)label('밤이 되었어요. 집으로 돌아가요!',W/2,H-15,'#77578c',20)}
function drawInside(){background(cozy.scene==='sleeping'?1:cozy.woke?2:0,0);if(cozy.scene!=='sleeping'&&!cozy.woke)drawPlayer();if(cozy.scene==='sleeping'){label('코오… '+Math.ceil(cozy.sleepLeft)+'초',W/2,100,'#ae7192',24);ctx.font='bold 30px ui-rounded,system-ui';ctx.fillStyle='#fff5ff';ctx.fillText('Z z z',310,190+Math.sin(animTime*2)*5)}else if(cozy.clock>=100)label('침대에서 포근하게 잠들어요',275,165,'#aa7595',19);else if(cozy.woke)label('좋은 아침!',W/2,90,'#b18a58',24);label('문 · 바깥으로',W/2,H-50,'#96766f',18)}
function frame(t){const dt=Math.min((t-lastTime)/1000||0,.05);lastTime=t;draw(dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
const keyMap={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName)||$('dialog').open)return;const k=keyMap[e.key]||keyMap[e.key.toLowerCase()];if(k){e.preventDefault();keys.add(k)}if(e.key==='e'||e.key==='E'||e.code==='Space'){e.preventDefault();interact()}});window.addEventListener('keyup',e=>{const k=keyMap[e.key]||keyMap[e.key.toLowerCase()];if(k)keys.delete(k)});window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden)keys.clear()});document.querySelectorAll('[data-direction]').forEach(b=>{const d=b.dataset.direction;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(d);b.classList.add('pressed')});const release=()=>{keys.delete(d);b.classList.remove('pressed')};for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,release)});
function interact(){if(cozy.scene==='inside'){if(cozy.clock>=100&&player.y<450)sleep();else exitHome();return}if(cozy.scene==='sleeping')return;let best=0,d=Infinity;state.tiles.forEach((t,i)=>{const p=cell(i),v=Math.hypot(player.x-p.x,player.y-p.y);if(v<d){best=i;d=v}});tileClick(best)}$('interact').onclick=interact;
canvas.addEventListener('click',e=>{if(state.paused||cozy.scene==='sleeping')return;const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)*W/b.width,y=(e.clientY-b.top)*H/b.height;if(cozy.scene==='inside'){if(y>H*.72&&x>W*.3&&x<W*.7)exitHome();else if(x<W*.55&&y<H*.65)sleep();return}const v=cozy.visitors.find(v=>Math.abs(x-v.x)<60&&y>v.y-115&&y<v.y+20);if(v){hitVisitor(v.id);return}const c=CATS.find(c=>Math.abs(x-c.x)<45&&y>c.y-85&&y<c.y+20);if(c){feedCat(c.id);return}const col=Math.floor((x-OX)/CW),row=Math.floor((y-OY)/CH);if(col>=0&&col<5&&row>=0&&row<4)tileClick(row*5+col)});
$('help').onclick=()=>open('<h2>우리 마을의 작은 하루</h2><p>방향 버튼이나 방향키로 걸어요. 화면 위 목표를 하나씩 완료해 보세요.</p><p>꼬마 나무꾼은 숲에 장착하면 일을 해요. 펫은 골드 없이 고를 수 있어요.</p><p>말썽 아저씨는 한 명당 5번 누르면 돌아가요.</p><p>약 100초가 지나 밤이 되면 집에 들어가 침대에서 자요. 6초 후 아침이 오면 문으로 나가요.</p><p>길고양이를 누르면 식량 1개로 밥을 줘요. 그 고양이는 잠들기 전까지 따라오고, 다음 날에는 다시 밥을 줘야 해요.</p><p>게임과 시간은 화면이 열려 있을 때 진행돼요. 이 기기에 자동 저장돼요.</p>');window.addEventListener('pagehide',saveStory);advanceStory();render();
